steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
        'build',
        '-t',
        # '' <-- el nombre de la imagen de docker
        'f',
        'Dockerfile.prod',
        '--platform=linux/amd64',
        '.',
      ]
  - name: 'gcr.io/cloudbuilders/docker'
    args: [
        'push',
        # <-- nombre de la imagen

      ]

options:
  logging: CLOUD_LOGGING_ONLY
