services:
  academy:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: 12345678
      POSTGRES_USER: postgres
    ports:
      - "5433:5433"
    command: "-p 5433"
  pgadmin:
    image: "dpage/pgadmin4"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.command
      PGADMIN_DEFAULT_PASSWORD: 12345678
    ports:
      - "5050:80"
    depends_on:
      - academy
