# 1.  Dependencias

FROM node:22-alpine AS deps

WORKDIR /usr/src/app

COPY package.json ./
COPY package-lock.json ./

RUN npm install

# 2. Build - Construir

FROM node:22-alpine AS build

WORKDIR /usr/src/app

COPY --from=deps /usr/src/app/node_modules ./node_modules

COPY . .

# 3. Test

RUN npm run build

RUN npm ci -f --only=production && npm cache clean --force

# 4. Prod

FROM node:22-alpine AS prod

WORKDIR /usr/src/app

COPY --from=build /usr/src/app/node_modules ./node_modules
COPY --from=build /usr/src/app/dist ./dist

ENV NODE_ENV=production

EXPOSE 3001

CMD ["node", "dist/main.js"]
